import React from "react";
import {
  TextFields as TextIcon,
  Lock as PasswordIcon,
  Email as EmailIcon,
  Numbers as NumberIcon,
  Notes as TextareaIcon,
  ArrowDropDownCircle as DropdownIcon,
  Language as CountryIcon,
  CheckBox as CheckboxIcon,
} from "@mui/icons-material";
import { PaletteItem } from "./types";

export const FIELD_PALETTE: PaletteItem[] = [
  {
    type: "text",
    label: "Text",
    icon: <TextIcon />,
    description: "Single-line text input",
  },
  {
    type: "email",
    label: "Email",
    icon: <EmailIcon />,
    description: "Email address field",
  },
  {
    type: "password",
    label: "Password",
    icon: <PasswordIcon />,
    description: "Masked password input",
  },
  {
    type: "number",
    label: "Number",
    icon: <NumberIcon />,
    description: "Numeric input with min/max",
  },
  {
    type: "textarea",
    label: "Text Area",
    icon: <TextareaIcon />,
    description: "Multi-line text input",
  },
  {
    type: "dropdown",
    label: "Dropdown",
    icon: <DropdownIcon />,
    description: "Searchable select from options",
  },
  {
    type: "country",
    label: "Country Selector",
    icon: <CountryIcon />,
    description: "Searchable country picker",
  },
  {
    type: "checkbox",
    label: "Checkbox",
    icon: <CheckboxIcon />,
    description: "Boolean toggle",
  },
];

export const COUNTRIES: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Denmark",
  "Egypt",
  "Ethiopia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kenya",
  "South Korea",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Vietnam",
];
