import { Moment } from "moment";

export const STEPS = [
  "Team & Overview",
  "Innovation Details",
  "Review & Submit",
];

export const INNOVATION_CATEGORIES = [
  "AI & ML (Artificial Intelligence & Machine Learning)",
  "Aerospace & Aviation",
  "Computer Science",
  "Energy & Environment",
  "Fintech (Financial Technology)",
  "Genomics and Biotechnology",
  "Health Science, Diagnostics and Biomarkers",
  "Neurotechnology and Brain Computer Interface",
  "Sustainability",
  "Others",
];

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const createDefaultMember = () => ({
  name: "",
  fatherName: "",
  fatherEmail: "",
  motherName: "",
  motherEmail: "",
  gender: "",
  dob: null as any, // Moment | null
  schoolName: "",
  schoolHeadEmail: "",
  schoolAddress: "",
  city: "",
  emirate: "",
});

export const getTextFieldStyles = (colors: any) => ({
  "& .MuiOutlinedInput-root": {
    color: colors.TEXT_PRIMARY,
    bgcolor: "transparent",
    borderRadius: "0px",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    fontSize: "0.95rem",
    fontWeight: 500,
    "& fieldset": {
      borderColor: colors.BORDER,
      borderRadius: "0px",
      transition: "all 0.3s ease",
    },
    "&:hover": {
      bgcolor: "transparent",
      "& fieldset": { borderColor: `${colors.PRIMARY}60` },
    },
    "&.Mui-focused": {
      bgcolor: "transparent",
      boxShadow: `0 8px 24px ${colors.PRIMARY}15`,
      "& fieldset": {
        borderColor: colors.PRIMARY,
        borderWidth: "2px",
      },
    },
    "& input::placeholder": {
      color: colors.TEXT_SECONDARY,
      opacity: 0.6,
      fontWeight: 400,
    },
  },
  "& .MuiInputLabel-root": {
    color: colors.TEXT_SECONDARY,
    fontSize: "0.85rem",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    "&.Mui-focused": { color: colors.PRIMARY },
  },
  "& .MuiFormLabel-root": {
    fontWeight: 700,
  },
  "& .MuiSelect-select, & .MuiInputBase-input": {
    padding: "18px 16px",
  },
  "& .MuiInputAdornment-root": {
    marginRight: "8px",
  },
});
